spring.application.name=unicloud-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/unicloud
spring.datasource.username=root
spring.datasource.password=balaji@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB